
export const icons ={
        logo: require('../assets/images/logo.png'),
        home: require('../assets/images/icons/home.png'),
        homeWhite: require('../assets/images/icons/home-white.png'),
        add: require('../assets/images/icons/add1.png'),
        addFocus: require('../assets/images/icons/add1-focus.png'),
        logout: require('../assets/images/icons/logout.png'),
        search: require('../assets/images/icons/lupa.png'),
        hen: require('../assets/images/icons/gallina.png'),
        rooster: require('../assets/images/icons/gallo.png'),
        in: require('../assets/images/marks/adentro.png'),
        out: require('../assets/images/marks/afuera.png'),
        both: require('../assets/images/marks/ambas.png'),
        none: require('../assets/images/marks/ninguna.png'),
        left: require('../assets/images/marks/izquierda.png'),
        right: require('../assets/images/marks/derecha.png'),
        bothNoise: require('../assets/images/marks/ambasNariz.png'),
        noneNoise: require('../assets/images/marks/sinNariz.png'),
        edit: require('../assets/images/icons/edit.png'),
       }